# Compile arguments
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.1.6.1
mod_group = it.hurts.octostudios.perception
mod_name = Perception
mod_id = perception
mod_description = Enriching the world with immersive visual effects
mod_authors = OctoStudios
mod_license = All Rights Reserved
mod_tracker = https://github.com/Octo-Studios/perception/issues
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.11

# Dependencies
shatterlib_version = 0.6.0.5+1.21.11
architectury_api_version = 19.0.1
fabric_loader_version = 0.18.4
fabric_api_version = 0.141.1+1.21.11
neoforge_version = 21.11.30-beta